<ul class="footer links contact-details">
    <h4>Contact Details</h4>
    <li class="phone">
        <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/002-phone-receiver.svg') ?>" alt="phone icon">
        <div class="info">
            <a>0203-980-14-70</a>
            <a>0203-478-12-96</a>
        </div>
    </li>
    <li class="email">
        <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/024-email.svg') ?>" alt="email icon">
        <div class="info">
            <a>vene@gmail.com</a>
            <a>venedor@mail.com</a>
        </div>
    </li>
    <li class="skype">
        <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/003-skype-logo.svg') ?>" alt="skype icon">
        <div class="info">
            <a>venedor_contact</a>
            <a>venedor_support</a>
        </div>
    </li>
</ul>
