<div class="instagram_blocks">
    <h4>Instagram</h4>
    <div class="upper">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
    </div>
    <div class="lower">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/block.svg') ?>" alt="email icon">
    </div>
</div>
