<div class="payments">
    <div class="payment-info">
        <h4>100% secure & Trusted Payment.</h4>
        <p>Need help? Call us at +0203-980-14+79 for any assistance required.</p>
    </div>
    <div class="payment-list">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/mastercard.png') ?>" alt="truck-icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/paypal.png') ?>" alt="truck-icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/american_express.png') ?>" alt="truck-icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/maestro.png') ?>" alt="truck-icon">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/visa.png') ?>" alt="truck-icon">
    </div>
</div>
