<div class="header-details">
    <div class="details-container">
        <div class="free-delivery">
            <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/004-delivery-truck-silhouette.svg') ?>"
                 alt="truck-icon">
            <div class="info">
                <h2>FREE DELIVERY</h2>
                <p>on orders over 100$</p>
            </div>
        </div>
        <div class="choose-a-free-gift">
            <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/gift.svg') ?>" alt="truck-icon">
            <div class="info">
                <h2>CHOOSE A FREE GIFT</h2>
                <p>with every purchase</p>
            </div>
        </div>
        <div class="secure-shopping">
            <img class="icon" src="<?= $this->getViewFileUrl('Magento_Theme::images/005-lock.svg') ?>" alt="truck-icon">
            <div class="info">
                <h2>100% SECURE SHOPPING</h2>
                <p>mauris ac pulvinar</p>
            </div>
        </div>
    </div>
</div>
